"""Compatibility facade for grounded resume compilation."""

from .construction.compiler import (
    EVIDENCE,
    HEADING,
    PREVIEW_NOTICE,
    SECTION_ALIASES,
    SKILL_LINE,
    STALE_PREVIEW_NOTICE,
    STORY,
    build_resume,
    compile_markdown,
    delimited,
    evidence_text,
    frontmatter,
    heading_blocks,
    list_blocks,
    main,
    mark_published_preview_stale,
    relative_output,
    sections,
    sha256_file,
    story_id,
)

__all__ = [
    "EVIDENCE",
    "HEADING",
    "PREVIEW_NOTICE",
    "SECTION_ALIASES",
    "SKILL_LINE",
    "STALE_PREVIEW_NOTICE",
    "STORY",
    "build_resume",
    "compile_markdown",
    "delimited",
    "evidence_text",
    "frontmatter",
    "heading_blocks",
    "list_blocks",
    "main",
    "mark_published_preview_stale",
    "relative_output",
    "sections",
    "sha256_file",
    "story_id",
]
