"""Compatibility facade for role-profile schema validation."""

from .role_profiles.schema import (
    ALLOWED_FIELDS,
    BASES,
    COPIED_LABEL_MIN_COVERAGE,
    MATURITIES,
    PAGE_FORMATS,
    SLUG,
    SOURCE_ID,
    SOURCE_KINDS,
    STATUSES,
    STYLE_MIN_CLAIM_BLOCKS,
    STYLE_MIN_TERM_OCCURRENCES,
    STYLE_MIN_WORD_SHARE,
    STYLE_TOKEN_EXCLUSIONS,
    iso_date,
    nonempty_string,
    parse_direction,
    string_list,
)

__all__ = [
    "ALLOWED_FIELDS",
    "BASES",
    "COPIED_LABEL_MIN_COVERAGE",
    "MATURITIES",
    "PAGE_FORMATS",
    "SLUG",
    "SOURCE_ID",
    "SOURCE_KINDS",
    "STATUSES",
    "STYLE_MIN_CLAIM_BLOCKS",
    "STYLE_MIN_TERM_OCCURRENCES",
    "STYLE_MIN_WORD_SHARE",
    "STYLE_TOKEN_EXCLUSIONS",
    "iso_date",
    "nonempty_string",
    "parse_direction",
    "string_list",
]
