"""Compatibility facade for job-to-resume matching."""

from .matching.audit import (
    CRITERION_FIELDS,
    IMPORTANCE,
    SEARCH_FIELDS,
    SOURCE_FIELDS,
    SOURCE_KINDS,
    TARGET_FIELDS,
    body_sha256,
    classify_match,
    compare_audits,
    exact_retrieval,
    main,
    markdown_report,
    match_job,
    parse_target,
    phrase_occurrences,
    project_target_path,
    resume_audit,
    target_paths,
    validate_main,
    validate_target,
)

__all__ = [
    "CRITERION_FIELDS",
    "IMPORTANCE",
    "SEARCH_FIELDS",
    "SOURCE_FIELDS",
    "SOURCE_KINDS",
    "TARGET_FIELDS",
    "body_sha256",
    "classify_match",
    "compare_audits",
    "exact_retrieval",
    "main",
    "markdown_report",
    "match_job",
    "parse_target",
    "phrase_occurrences",
    "project_target_path",
    "resume_audit",
    "target_paths",
    "validate_main",
    "validate_target",
]
