"""Compatibility facade for legacy career-vault migration."""

from .vault.legacy_migration import (
    CATEGORY_FILES,
    FACT_HEADING,
    FIELD,
    SLUG,
    MigrationPlan,
    apply_migration_plan,
    build_migration_plan,
    copy_recovery_backup,
    main,
    meaningful_unparsed,
    parse_facts,
    parse_facts_with_unmatched,
    quote,
    render_employment,
    render_fact,
    render_staged_vault,
    sha256_file,
    split_frontmatter,
    validate_legacy_fact,
    validate_vault,
)

__all__ = [
    "CATEGORY_FILES",
    "FACT_HEADING",
    "FIELD",
    "SLUG",
    "MigrationPlan",
    "apply_migration_plan",
    "build_migration_plan",
    "copy_recovery_backup",
    "main",
    "meaningful_unparsed",
    "parse_facts",
    "parse_facts_with_unmatched",
    "quote",
    "render_employment",
    "render_fact",
    "render_staged_vault",
    "sha256_file",
    "split_frontmatter",
    "validate_legacy_fact",
    "validate_vault",
]
