"""Compatibility facade for safe resume HTML rendering."""

from .resume_documents.html import (
    PAGE_FORMATS,
    PLACEHOLDER,
    SECTION_TITLES,
    contact_html,
    contained_project_path,
    escaped,
    evidence,
    evidence_attribute,
    known_fact_ids,
    load_payload,
    main,
    object_list,
    object_value,
    render_payload,
    review_block_id,
    review_label,
    review_panel,
    review_text,
    safe_link,
    section,
    text,
)

__all__ = [
    "PAGE_FORMATS",
    "PLACEHOLDER",
    "SECTION_TITLES",
    "contact_html",
    "contained_project_path",
    "escaped",
    "evidence",
    "evidence_attribute",
    "known_fact_ids",
    "load_payload",
    "main",
    "object_list",
    "object_value",
    "render_payload",
    "review_block_id",
    "review_label",
    "review_panel",
    "review_text",
    "safe_link",
    "section",
    "text",
]
