"""Compatibility facade for additive career-source registration."""

from .vault.source_import import (
    DOCUMENT_KINDS,
    SUPPORTED,
    WORD_NAMESPACE,
    ImportPlan,
    LayoutError,
    TextHTMLParser,
    VaultLayout,
    apply_import_plan,
    build_import_plan,
    extract_docx_textboxes,
    extract_text,
    is_metadata_name,
    iter_sources,
    load_manifest,
    main,
    matches_any,
    normalize_text,
    resume_manifest_sources,
    sha256_bytes,
    snapshot_content,
)

__all__ = [
    "DOCUMENT_KINDS",
    "SUPPORTED",
    "WORD_NAMESPACE",
    "ImportPlan",
    "LayoutError",
    "TextHTMLParser",
    "VaultLayout",
    "apply_import_plan",
    "build_import_plan",
    "extract_docx_textboxes",
    "extract_text",
    "is_metadata_name",
    "iter_sources",
    "load_manifest",
    "main",
    "matches_any",
    "normalize_text",
    "resume_manifest_sources",
    "sha256_bytes",
    "snapshot_content",
]
