"""Compatibility facade for career-vault validation."""

from .vault.validation import (
    ALLOWED_CATEGORIES,
    ALLOWED_FORMATS,
    ALLOWED_STATUSES,
    ALLOWED_TYPES,
    FACT_ID,
    LIST_FIELDS,
    SHA256,
    SOURCE_ID,
    empty_result,
    format_summary,
    main,
    parse_frontmatter,
    read_json,
    scalar,
    sha256_bytes,
    string_list,
    validate_sources,
    validate_vault,
)

__all__ = [
    "ALLOWED_CATEGORIES",
    "ALLOWED_FORMATS",
    "ALLOWED_STATUSES",
    "ALLOWED_TYPES",
    "FACT_ID",
    "LIST_FIELDS",
    "SHA256",
    "SOURCE_ID",
    "empty_result",
    "format_summary",
    "main",
    "parse_frontmatter",
    "read_json",
    "scalar",
    "sha256_bytes",
    "string_list",
    "validate_sources",
    "validate_vault",
]
