import importlib

import pytest

FACADE_EXPORTS = {
    "agent": {"AGENT_INSTRUCTIONS", "AgentService", "ConsoleAdapter", "main"},
    "agent_config": {
        "DEFAULT_AGENT_CONFIG",
        "DEFAULT_FAST_MODEL",
        "LEGACY_GENERATED_FAST_MODELS",
        "AgentChannels",
        "AgentConfig",
        "AgentLimits",
        "AgentModels",
        "AgentRouting",
        "TelegramChannel",
        "load_agent_config",
        "render_default_agent_config",
    },
    "agent_openrouter": {"AgentProviderError", "OPENROUTER_BASE_URL", "OpenRouterAdapter"},
    "agent_state": {"AgentState", "StoredUpdate", "default_agent_state_path"},
    "agent_telegram": {
        "LOGGER",
        "TELEGRAM_CHUNK_SIZE",
        "TELEGRAM_MESSAGE_LIMIT",
        "AgentResponder",
        "TelegramAdapter",
        "discover_telegram_ids",
        "run_telegram_service",
        "split_message",
        "validate_telegram_configuration",
        "verify_telegram_identity",
    },
    "agent_tools": {"build_job_screening_tools", "build_read_only_tools"},
    "applications": {
        "ANSWER_STATES",
        "DEFAULT_ROOT",
        "INTERVIEW_STATUSES",
        "OFFER_STATUSES",
        "RATE_SAMPLE_FLOOR",
        "RESUME_SNAPSHOT_ROOT",
        "SCHEMA_VERSION",
        "STATUSES",
        "TERMINAL_STATUSES",
        "_write_or_preview",
        "append_answer",
        "append_event",
        "application_job_dispositions",
        "applied_job_ids",
        "build_automated_record",
        "build_record",
        "current_application_status",
        "find_answers",
        "iter_records",
        "load_record",
        "main",
        "migrate_dispositions",
        "outcome_report",
        "parser",
        "preserve_application_resume_snapshots",
        "reapplication_opportunities",
        "record_application",
        "validate_history",
        "validate_record",
    },
    "artifact_paths": {"default_resume_output_base", "resume_output_base"},
    "artifact_status": {
        "ArtifactStatus",
        "build_manifest_freshness",
        "load_json_object",
        "record_freshness",
        "relative_path",
        "sha256",
    },
    "project_report": {
        "_build_status",
        "_initial_draft_readiness",
        "_match_status",
        "_mint_status",
        "_next_action",
        "_onboarding_status",
        "_preview_status",
        "_resume_records",
        "_review_status",
        "_slugify",
        "_status",
        "_target_records",
        "format_summary",
        "main",
        "project_report",
        "validate_vault",
    },
    "previewing": {
        "APPROVED_NOTICE",
        "ATTENTION_NOTICE",
        "PRESENTATION_POLICY",
        "PREVIEW_MODE",
        "_current_build",
        "_current_career_review",
        "_handoff_presentation",
        "_job_context",
        "_match_feedback",
        "_render_handoff_markdown",
        "_require_resolved_role_balance",
        "main",
        "preview_resume",
    },
    "verification": {
        "_cached_receipt",
        "_load_json",
        "_optional_path_record",
        "_path_record",
        "_preview_freshness",
        "_record_freshness",
        "build_manifest_freshness",
        "main",
        "verify_resume",
        "workflow_state",
    },
    "minting": {
        "_filename_part",
        "_submission_path",
        "main",
        "mint_resume",
        "render_pdf",
    },
    "report_policy": {
        "_initial_draft_readiness",
        "_next_action",
        "_onboarding_status",
    },
    "web_filters": {"FilterTerm", "ViewFilters", "matches_view"},
    "web_career": {
        "_all_evidence_ids",
        "_direction_label",
        "_display_name",
        "_headline_parts",
        "_preview_url",
        "_render_portal_preview",
        "_without_workflow_notice",
        "archive_directional_resume",
        "directional_resume_removal_impact",
        "list_resumes",
        "resolve_application_resume_preview",
        "resolve_directional_resume_reference",
        "resolve_resume_preview",
        "resolve_retired_resume_reference",
        "restore_directional_resume",
    },
    "web_agent": {"install_assistant"},
    "web": {"create_app", "main"},
    "web_agent_resume": {
        "LanguageBlock",
        "LanguageDecisions",
        "WordingCheck",
        "apply_wording",
        "digest",
        "read_resume",
        "replacement_source",
        "resume_path",
    },
    "web_agent_state": {"WebAgentState", "_now"},
    "web_agent_worker": {
        "WEB_INSTRUCTIONS",
        "_instructions_for_window",
        "main",
        "run_proposal",
        "run_turn",
    },
    "web_integrations": {
        "GMAIL_CLIENT_MAX_BYTES",
        "OAUTH_SESSION_TIMEOUT_SECONDS",
        "TELEGRAM_PAIRING_TIMEOUT_SECONDS",
        "GmailOAuthSession",
        "PortalIntegrationService",
        "TelegramPairingSession",
    },
    "web_job_sources": {
        "CONFIG",
        "LOCK",
        "NAMES",
        "STATE",
        "_lock",
        "run_worker",
        "source_status",
        "start_scan",
        "toggle_source",
    },
    "web_schedule": {
        "DEFAULT_REPLENISHMENT_STATE",
        "DEFAULT_SCREENING_OUTPUT",
        "_current_job_stage",
        "_default_config",
        "_default_timezone",
        "_load",
        "_state_status",
        "save_schedule",
        "schedule_status",
    },
    "web_system": {"system_status"},
    "web_service": {
        "APPLICATIONS_ROOT",
        "DATE_RANGES",
        "EMPLOYMENT_TYPES",
        "HIDDEN_POSTINGS_PATH",
        "InventoryLoader",
        "JOBS_CONFIG",
        "JOB_FEEDBACK_ACTIONS",
        "JOB_FEEDBACK_PATH",
        "JOB_FEEDBACK_REASONS",
        "JOB_HIDE_REASONS",
        "JOB_SCREENING_OUTPUT",
        "LOGGER",
        "MAJOR_EMPLOYER_TAG_PREFIXES",
        "MAX_RESUME_BYTES",
        "ONBOARDING_STATE_PATH",
        "OPENROUTER_SECRET_PATH",
        "RECOMMENDATION_SHELF_SIZE",
        "STATE_PATH",
        "TITLE_GENERATION_CACHE_PATH",
        "TOP_WORKPLACE_TAG_PREFIXES",
        "WORK_MODES",
        "DashboardService",
        "ScreeningInputError",
        "_clean_description",
        "_company_recognition",
        "_employment_categories",
        "_job_timestamp",
        "_raise_screening_input_error",
    },
    "ats": {"REPLACEMENTS", "normalize_payload", "normalize_text"},
    "ats_readability": {
        "MAX_RECOMMENDED_BYTES",
        "REPORT_VERSION",
        "SECTION_TITLES",
        "ReadabilityCheck",
        "build_ats_readability_report",
    },
    "automation_config": {
        "DEFAULT_CONFIG",
        "DEFAULT_GMAIL_INTERVAL_HOURS",
        "DEFAULT_JOB_TIMES",
        "AutomationConfig",
        "GmailSchedule",
        "JobSchedule",
        "NotificationConfig",
        "config_payload",
        "configure",
        "load_config",
        "render_default_config",
    },
    "automation": {
        "DEFAULT_CONFIG",
        "AutomationConfig",
        "AutomationService",
        "AutomationState",
        "GmailSchedule",
        "JobSchedule",
        "Notification",
        "NotificationConfig",
        "TaskExecutionError",
        "_configure_logging",
        "_in_quiet_hours",
        "_run_jobs",
        "config_payload",
        "configure",
        "default_state_path",
        "gmail_notification",
        "job_notification",
        "load_config",
        "main",
        "next_job_run",
        "reapplication_notification",
        "render_default_config",
        "run_forever",
    },
    "background_screening": {
        "DEFAULT_OPENROUTER_SECRET",
        "DEFAULT_REPLENISHMENT_LOCK",
        "DEFAULT_REPLENISHMENT_STATE",
        "DEFAULT_SCREENING_CACHE",
        "DEFAULT_SCREENING_OUTPUT",
        "background_screening_configured",
        "prepare_background_screening_input",
        "publish_replenishment_state",
        "replenishment_running",
        "run_background_quick_screening",
        "run_background_replenishment",
    },
    "compilation": {
        "EVIDENCE",
        "HEADING",
        "PREVIEW_NOTICE",
        "SECTION_ALIASES",
        "SKILL_LINE",
        "STALE_PREVIEW_NOTICE",
        "STORY",
        "build_resume",
        "compile_markdown",
        "delimited",
        "evidence_text",
        "frontmatter",
        "heading_blocks",
        "list_blocks",
        "main",
        "mark_published_preview_stale",
        "relative_output",
        "sections",
        "sha256_file",
        "story_id",
    },
    "resume_templates": {
        "LEGACY_SECTION_PLACEHOLDERS",
        "THEME_CSS_PLACEHOLDER",
        "THEME_KINDS",
        "THEME_REQUIRED_PLACEHOLDERS",
        "THEME_STYLE_PLACEHOLDERS",
        "load_content_template",
        "load_rendering_theme",
        "rendering_theme_text",
        "scaffold_template",
        "select_catalog_item",
        "template_catalog",
    },
    "directions": {
        "ALLOWED_FIELDS",
        "BASES",
        "COPIED_LABEL_MIN_COVERAGE",
        "MATURITIES",
        "PAGE_FORMATS",
        "SLUG",
        "SOURCE_ID",
        "SOURCE_KINDS",
        "STATUSES",
        "STYLE_MIN_CLAIM_BLOCKS",
        "STYLE_MIN_TERM_OCCURRENCES",
        "STYLE_MIN_WORD_SHARE",
        "STYLE_TOKEN_EXCLUSIONS",
        "audit_direction",
        "direction_style_diagnostics",
        "fact_themes",
        "iso_date",
        "main",
        "nonempty_string",
        "normalize_phrase",
        "parse_direction",
        "phrase_present",
        "preview_direction_creation",
        "profile_paths",
        "project_direction_path",
        "string_list",
        "theme_reference_warnings",
    },
    "evidence": {
        "ASSERTION_VERBS",
        "LEADING_WORD",
        "LOW_INFORMATION_LEADS",
        "NUMBER",
        "STOP_WORDS",
        "WORD",
        "FactEvidence",
        "audit_claims",
        "claim_blocks",
        "load_fact_evidence",
        "meaningful_words",
        "normalized_numbers",
        "unsupported_assertion_verbs",
    },
    "evidence_questions": {
        "GAP_KEY",
        "GAP_TYPES",
        "GENERIC_PROMPTS",
        "RESOLUTIONS",
        "SOURCE_ID",
        "open_questions",
        "question_plan",
        "resolve_question",
    },
    "feedback_memory": {
        "KINDS",
        "PROMOTIONS",
        "RULE_ID",
        "RULE_STATUSES",
        "SCOPE_LEVELS",
        "SESSION_ID",
        "SESSION_STATUSES",
        "STRENGTHS",
        "SUBJECT_KEY",
        "accept_feedback",
        "guidance_snapshot",
        "main",
        "manifest_guidance_freshness",
        "record_feedback",
        "resolve_feedback",
        "resolve_for_plan",
        "retire_feedback_rule",
        "validate_feedback_memory",
    },
    "gmail_automation": {
        "CLASSIFIER_VERSION",
        "DEFAULT_SCAN_QUERY",
        "GMAIL_API_URL",
        "GMAIL_READONLY_SCOPE",
        "GmailLifecycleEvent",
        "GmailMessage",
        "GmailRuntimeState",
        "_inventory",
        "_resolve_existing_application",
        "classify_lifecycle_event",
        "default_state_path",
        "default_token_path",
        "main",
        "parse_message",
        "process_messages",
        "scan",
    },
    "gmail_state": {
        "CLASSIFIER_VERSION",
        "GmailMessage",
        "GmailRuntimeState",
        "sender_domain_hash",
    },
    "jobs": {
        "DEFAULT_CONFIG",
        "DEFAULT_LATEST_REFRESH",
        "DEFAULT_NEW_OUTPUT",
        "DEFAULT_NEW_REVIEW_OUTPUT",
        "DEFAULT_OUTPUT",
        "DEFAULT_PREFERENCES",
        "DEFAULT_PROVIDER_COMPARISON",
        "DEFAULT_REVIEW_OUTPUT",
        "get_job_screening_packet",
        "main",
        "parser",
    },
    "job_report": {"markdown_report"},
    "layout": {
        "DEFAULT_CONFIG",
        "SCHEMA_VERSION",
        "LayoutError",
        "VaultLayout",
        "contained_path",
        "load_json_object",
        "relative_path",
    },
    "match_grading": {
        "CASE_FIELDS",
        "IMPORTANCE",
        "JUDGMENT_FIELDS",
        "MATCH_LABELS",
        "REQUIREMENT_TYPES",
        "STATUSES",
        "SUFFICIENCY",
        "classify_match",
        "load_classification_case",
        "validate_against_match",
        "validate_classification_case",
    },
    "migration": {
        "CATEGORY_FILES",
        "FACT_HEADING",
        "FIELD",
        "SLUG",
        "MigrationPlan",
        "apply_migration_plan",
        "build_migration_plan",
        "copy_recovery_backup",
        "main",
        "meaningful_unparsed",
        "parse_facts",
        "parse_facts_with_unmatched",
        "quote",
        "render_employment",
        "render_fact",
        "render_staged_vault",
        "sha256_file",
        "split_frontmatter",
        "validate_legacy_fact",
        "validate_vault",
    },
    "plans": {
        "LayoutError",
        "PlannedWrite",
        "VaultChangePlan",
        "VaultLayout",
        "affected_references",
        "apply_plan",
        "file_sha256",
        "load_plan",
        "main",
        "plan_summary",
        "validate_staged_plan",
    },
    "pdf_rendering": {
        "BAD_GLYPHS",
        "audit_pdf",
        "extraction_blocks",
        "normalized_tokens",
        "render_pdf",
        "tokens_recovered",
    },
    "rendering": {
        "PAGE_FORMATS",
        "PLACEHOLDER",
        "SECTION_TITLES",
        "contact_html",
        "contained_project_path",
        "escaped",
        "evidence",
        "evidence_attribute",
        "known_fact_ids",
        "load_payload",
        "main",
        "object_list",
        "object_value",
        "render_payload",
        "review_block_id",
        "review_label",
        "review_panel",
        "review_text",
        "safe_link",
        "section",
        "text",
    },
    "resume_parser": {
        "EVIDENCE",
        "HEADING",
        "SECTION_ALIASES",
        "SKILL_LINE",
        "STORY",
        "compile_markdown",
        "delimited",
        "evidence_text",
        "frontmatter",
        "heading_blocks",
        "list_blocks",
        "sections",
        "story_id",
    },
    "schema_upgrade": {
        "SchemaUpgradePlan",
        "apply_upgrade_plan",
        "build_upgrade_plan",
        "create_backup",
        "insert_scope",
        "load_role_map",
        "main",
        "read_v1_config",
        "validate_staged_upgrade",
        "validate_vault",
    },
    "service": {
        "SUPERVISOR_CONFIG_ENV",
        "main",
        "managed_service_status",
        "render_supervisor_config",
        "set_scheduler_enabled",
        "telegram_configuration_status",
    },
    "source_import": {
        "DOCUMENT_KINDS",
        "SUPPORTED",
        "WORD_NAMESPACE",
        "ImportPlan",
        "LayoutError",
        "TextHTMLParser",
        "VaultLayout",
        "apply_import_plan",
        "build_import_plan",
        "extract_docx_textboxes",
        "extract_text",
        "is_metadata_name",
        "iter_sources",
        "load_manifest",
        "main",
        "matches_any",
        "normalize_text",
        "resume_manifest_sources",
        "sha256_bytes",
        "snapshot_content",
    },
    "gmail_semantic": {
        "ACTIONABLE_EVENT_TYPES",
        "MAX_SEMANTIC_BODY_CHARS",
        "SemanticEmailClassifier",
        "SemanticEventType",
        "SemanticLifecycleDecision",
        "SemanticLifecycleOutcome",
        "minimize_message",
    },
    "review_records": {
        "BLOCK_ID",
        "EDITORIAL_DECISIONS",
        "EDITORIAL_SCOPE",
        "EDITORIAL_STATUSES",
        "EVIDENCE_STATUSES",
        "EditorialBlock",
        "FEEDBACK_DECISIONS",
        "FEEDBACK_STATUSES",
        "FeedbackRuleDecision",
        "HIRING_READS",
        "NarrativeReviewBlock",
        "REVIEW_METHODS",
        "ROUTES",
        "ReviewInput",
        "ReviewRecord",
        "SHA256",
        "VERDICTS",
        "apply_review_repairs",
        "build_review_package",
        "finalize_review_record",
        "load_review_record",
        "main",
        "narrative_block_inventory",
        "narrative_block_inventory_from_markdown",
        "narrative_blocks",
        "require_editorial_approval",
        "review_freshness",
        "sha256_file",
        "sha256_text",
    },
    "synthesis": {
        "CLAIM_COMPOSITIONS",
        "COMPETENCY_DECISIONS",
        "FIT_STATUSES",
        "PAGE_BUDGET_SOURCES",
        "RISK_STATUSES",
        "ROLE_ARC_EMPHASES",
        "SECTIONS",
        "STORY_ID",
        "TARGET_MODES",
        "ClaimEvidence",
        "ClaimSpec",
        "ConceptFit",
        "OmittedRoleSignal",
        "PageBudget",
        "PresentationStrategy",
        "ReviewerRisk",
        "RoleArc",
        "SynthesisPlan",
        "SynthesisStory",
        "audit_synthesis",
        "body_evidence_ids",
        "direction_concept_ids",
        "direction_page_budget",
        "exact_fields",
        "fact_metadata",
        "load_synthesis_plan",
        "main",
        "nonempty_string",
        "object_value",
        "optional_string",
        "role_arc_payloads",
        "sha256_file",
        "string_list",
    },
    "validation": {
        "ALLOWED_CATEGORIES",
        "ALLOWED_FORMATS",
        "ALLOWED_STATUSES",
        "ALLOWED_TYPES",
        "FACT_ID",
        "LIST_FIELDS",
        "SHA256",
        "SOURCE_ID",
        "empty_result",
        "format_summary",
        "main",
        "parse_frontmatter",
        "read_json",
        "scalar",
        "sha256_bytes",
        "string_list",
        "validate_sources",
        "validate_vault",
    },
    "workspace": {
        "CommandResult",
        "WorkspaceError",
        "WorkspaceInitResult",
        "connect_existing_workspace",
        "default_github_repository",
        "discover_workspace",
        "github_repository_from_remote",
        "initialize_workspace",
        "main",
        "run_command",
        "status_main",
        "sync_workspace_templates",
        "workspace_status",
    },
    "workspace_state": {
        "DEFAULT_VAULT_REPOSITORY_NAME",
        "DEFAULT_WORKSPACE",
        "GITHUB_OWNER",
        "GITHUB_REMOTES",
        "GITHUB_REPOSITORY",
        "WORKSPACE_CONFIG",
        "WORKSPACE_VERSION",
        "CommandResult",
        "Runner",
        "WorkspaceError",
        "WorkspaceInitResult",
        "default_github_repository",
        "discover_workspace",
        "github_repository_from_remote",
        "run_command",
        "workspace_status",
    },
    "workspace_templates": {
        "sync_templates",
        "template_resources",
        "write_workspace_files",
    },
}


@pytest.mark.parametrize(("module_name", "expected"), FACADE_EXPORTS.items())
def test_refactored_facade_preserves_legacy_exports(
    module_name: str,
    expected: set[str],
) -> None:
    module = importlib.import_module(f"resume_builder.{module_name}")

    assert expected <= set(module.__all__)
    assert not [name for name in sorted(expected) if not hasattr(module, name)]
