import importlib

import pytest

FACADE_EXPORTS = {
    "applications": {
        "ANSWER_STATES",
        "DEFAULT_ROOT",
        "INTERVIEW_STATUSES",
        "OFFER_STATUSES",
        "RATE_SAMPLE_FLOOR",
        "RESUME_SNAPSHOT_ROOT",
        "SCHEMA_VERSION",
        "STATUSES",
        "TERMINAL_STATUSES",
        "_write_or_preview",
        "append_answer",
        "append_event",
        "application_job_dispositions",
        "applied_job_ids",
        "build_automated_record",
        "build_record",
        "current_application_status",
        "find_answers",
        "iter_records",
        "load_record",
        "main",
        "migrate_dispositions",
        "outcome_report",
        "parser",
        "preserve_application_resume_snapshots",
        "reapplication_opportunities",
        "record_application",
        "validate_history",
        "validate_record",
    },
    "compilation": {
        "EVIDENCE",
        "HEADING",
        "PREVIEW_NOTICE",
        "SECTION_ALIASES",
        "SKILL_LINE",
        "STALE_PREVIEW_NOTICE",
        "STORY",
        "build_resume",
        "compile_markdown",
        "delimited",
        "evidence_text",
        "frontmatter",
        "heading_blocks",
        "list_blocks",
        "main",
        "mark_published_preview_stale",
        "relative_output",
        "sections",
        "sha256_file",
        "story_id",
    },
    "directions": {
        "ALLOWED_FIELDS",
        "BASES",
        "COPIED_LABEL_MIN_COVERAGE",
        "MATURITIES",
        "PAGE_FORMATS",
        "SLUG",
        "SOURCE_ID",
        "SOURCE_KINDS",
        "STATUSES",
        "STYLE_MIN_CLAIM_BLOCKS",
        "STYLE_MIN_TERM_OCCURRENCES",
        "STYLE_MIN_WORD_SHARE",
        "STYLE_TOKEN_EXCLUSIONS",
        "audit_direction",
        "direction_style_diagnostics",
        "fact_themes",
        "iso_date",
        "main",
        "nonempty_string",
        "normalize_phrase",
        "parse_direction",
        "phrase_present",
        "preview_direction_creation",
        "profile_paths",
        "project_direction_path",
        "string_list",
        "theme_reference_warnings",
    },
    "feedback_memory": {
        "KINDS",
        "PROMOTIONS",
        "RULE_ID",
        "RULE_STATUSES",
        "SCOPE_LEVELS",
        "SESSION_ID",
        "SESSION_STATUSES",
        "STRENGTHS",
        "SUBJECT_KEY",
        "accept_feedback",
        "guidance_snapshot",
        "main",
        "manifest_guidance_freshness",
        "record_feedback",
        "resolve_feedback",
        "resolve_for_plan",
        "retire_feedback_rule",
        "validate_feedback_memory",
    },
    "jobs": {
        "DEFAULT_CONFIG",
        "DEFAULT_LATEST_REFRESH",
        "DEFAULT_NEW_OUTPUT",
        "DEFAULT_NEW_REVIEW_OUTPUT",
        "DEFAULT_OUTPUT",
        "DEFAULT_PREFERENCES",
        "DEFAULT_PROVIDER_COMPARISON",
        "DEFAULT_REVIEW_OUTPUT",
        "get_job_screening_packet",
        "main",
        "parser",
    },
    "job_report": {"markdown_report"},
    "match_grading": {
        "CASE_FIELDS",
        "IMPORTANCE",
        "JUDGMENT_FIELDS",
        "MATCH_LABELS",
        "REQUIREMENT_TYPES",
        "STATUSES",
        "SUFFICIENCY",
        "classify_match",
        "load_classification_case",
        "validate_against_match",
        "validate_classification_case",
    },
    "gmail_semantic": {
        "ACTIONABLE_EVENT_TYPES",
        "MAX_SEMANTIC_BODY_CHARS",
        "SemanticEmailClassifier",
        "SemanticEventType",
        "SemanticLifecycleDecision",
        "SemanticLifecycleOutcome",
        "minimize_message",
    },
    "review_records": {
        "BLOCK_ID",
        "EDITORIAL_DECISIONS",
        "EDITORIAL_SCOPE",
        "EDITORIAL_STATUSES",
        "EVIDENCE_STATUSES",
        "EditorialBlock",
        "FEEDBACK_DECISIONS",
        "FEEDBACK_STATUSES",
        "FeedbackRuleDecision",
        "HIRING_READS",
        "NarrativeReviewBlock",
        "REVIEW_METHODS",
        "ROUTES",
        "ReviewInput",
        "ReviewRecord",
        "SHA256",
        "VERDICTS",
        "apply_review_repairs",
        "build_review_package",
        "finalize_review_record",
        "load_review_record",
        "main",
        "narrative_block_inventory",
        "narrative_block_inventory_from_markdown",
        "narrative_blocks",
        "require_editorial_approval",
        "review_freshness",
        "sha256_file",
        "sha256_text",
    },
    "synthesis": {
        "CLAIM_COMPOSITIONS",
        "COMPETENCY_DECISIONS",
        "FIT_STATUSES",
        "PAGE_BUDGET_SOURCES",
        "RISK_STATUSES",
        "ROLE_ARC_EMPHASES",
        "SECTIONS",
        "STORY_ID",
        "TARGET_MODES",
        "ClaimEvidence",
        "ClaimSpec",
        "ConceptFit",
        "OmittedRoleSignal",
        "PageBudget",
        "PresentationStrategy",
        "ReviewerRisk",
        "RoleArc",
        "SynthesisPlan",
        "SynthesisStory",
        "audit_synthesis",
        "body_evidence_ids",
        "direction_concept_ids",
        "direction_page_budget",
        "exact_fields",
        "fact_metadata",
        "load_synthesis_plan",
        "main",
        "nonempty_string",
        "object_value",
        "optional_string",
        "role_arc_payloads",
        "sha256_file",
        "string_list",
    },
}


@pytest.mark.parametrize(("module_name", "expected"), FACADE_EXPORTS.items())
def test_refactored_facade_preserves_legacy_exports(
    module_name: str,
    expected: set[str],
) -> None:
    module = importlib.import_module(f"resume_builder.{module_name}")

    assert expected <= set(module.__all__)
    assert not [name for name in sorted(expected) if not hasattr(module, name)]
